export const ButtonEnums = {
  PRIMARY: 'Primary',
  SECONDARY: 'Secondary',
  OUTLINE: 'Outline',
  GHOST: 'Ghost',
  LINK: 'Link',
  DANGER: 'Danger',
  ROUNDEDOUTLINE: 'RoundedOutline',
  ROUNDED: 'Rounded',
}
export const TypographyVariants = {
  Heading1: 36,
  Heading2: 24,
  TableText: 16,
  TableTextSize: 14,
  PopUpHeading: 24,
  PopUpText: 16,
  PageHeading: 30,
  PageSecondText: 16,
  h2: 46,
  h1: 54,
  h3: 40,
  h4: 20,
  h5: 18,
  h6: 48,
  h7: 64,
  h8: 32,
  h9: 25,
}

export const TypographyEnums = {
  HEADING1: 'Heading1',
  HEADING2: 'Heading2',
  TABLETEXT: 'TableText',
  TABLETEXTSIZE: 'TableTextSize',
  POPUPHEADING: 'PopUpHeading',
  POPUPTEXT: 'PopUpText',
  PAGEHEADING: 'PageHeading',
  PAGESECONDTEXT: 'PageSecondText',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  H5: 'h5',
  H6: 'h6',
  H7: 'h7',
  H8: 'h8',
  H9: 'h9',
}
