// export { default as SearchIcon } from './svg/search.svg'
// export { default as CloseIcon } from './svg/close.svg'
// export { default as UserIcon } from './svg/user.svg'
// export { default as ArrowRightIcon } from './svg/arrow-right.svg'
// export { default as SettingsIcon } from './svg/settings.svg'
// export { default as BarCharts } from './svg/barCharts.svg'
export { default as ArrowDown } from './svg/ArrowDown.svg'
export { default as CheckCircle } from './svg/CheckCircle.svg'
export { default as Eye } from './svg/Eye.svg'
export { default as Facebook } from './svg/Facebook.svg'
export { default as Vector } from './svg/Vector.svg'
export { default as Insta } from './svg/Insta.svg'
export { default as Linked } from './svg/Linked.svg'
export { default as ListView } from './svg/ListView.svg'
export { default as Setting } from './svg/Setting.svg'
export { default as Funnel } from './svg/Funnel.svg'
export { default as Heart } from './svg/Heart.svg'
export { default as Search } from './svg/Search.svg'
export { default as DownDown } from './svg/DownDown.svg'
export { default as Plus } from './svg/Plus.svg'
export { default as Action } from './svg/Action.svg'
export { default as Clip } from './svg/Clip.svg'
export { default as ChartLine } from './svg/ChartLine.svg'
export { default as share } from './svg/share.svg'


